name: goals_unlimited

description: "A Flutter app to track and manage your goals effectively."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.7.2
  lottie_onboarding_screen: ^1.0.0
  lottie: ^3.3.0
  intl_phone_field: ^3.2.0
  action_slider: ^0.7.0
  pinput: ^5.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
